name: Terraform Workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  TF_VERSION: "1.5.0" # Update this to your Terraform version
  TF_WORKING_DIR: "." # Directory containing your Terraform files
  AWS_REGION: "us-east-1" # Update this to your AWS region

jobs:
  terraform:
    name: "Terraform CI/CD"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
    # Step 1: Checkout the code
    - name: "Checkout code"
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: "Set up Terraform"
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Step 3: Terraform Init
    - name: "Terraform Init"
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}

    # Step 4: Terraform Format (Check formatting)
    - name: "Terraform Format"
      run: terraform fmt -check

    # Step 5: Terraform Validate (Check syntax and configuration)
    - name: "Terraform Validate"
      run: terraform validate

    # Step 6: Terraform Plan (Generate execution plan)
    - name: "Terraform Plan"
      id: plan
      run: terraform plan -out=tfplan

    # Step 7: Upload Plan (For PR and visibility)
    - name: "Upload Terraform Plan"
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: tfplan

  deploy:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    environment: production

    steps:
    # Step 1: Checkout the code
    - name: "Checkout code"
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: "Set up Terraform"
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Step 3: Terraform Init
    - name: "Terraform Init"
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}

    # Step 4: Terraform Apply (Auto-approve)
    - name: "Terraform Apply"
      run: terraform apply -auto-approve "tfplan"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}
